version: "3.7"
services:
  mysqldb:
    container_name: mysqldb
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .mysqldb:/data/mysql

  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/userdb?allowPublicKeyRetrieval=true&useSSL=false
    depends_on:
      - mysqldb